apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-preview
  template:
    metadata:
      labels:
        app: frontend-preview
    spec:
      containers:
        - name: frontend-preview
          image: ghcr.io/danielfmortensen/fortune-cookie-group1-frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_DNS
              value: backend-preview
            - name: BACKEND_PORT
              value: "9000"
      imagePullSecrets:
        - name: ghcr-secret