apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-preview
  template:
    metadata:
      labels:
        app: frontend-preview
    spec:
      containers:
        - name: frontend-preview
          image: ghcr.io/danielfmortensen/fortune-cookie-group1-frontend:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
        - name: frontend-preview
          image: ghcr.io/danielfmortensen/fortune-cookie-group1-frontend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: frontend-config-preview
      imagePullSecrets:
        - name: ghcr-secret