name: Build and Test Template

on:
  workflow_call:
    inputs:
      push_latest:
        required: true
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build and Test Frontend
        working-directory: ./frontend
        run: |
          go build -v ./...
          go test -v ./...

      - name: Build Backend
        working-directory: ./backend
        run: |
          go build -v ./...
          go test -v ./...

  delivery:
    needs: integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [backend, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Set lower case image name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }}-${{ matrix.service }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.service }}/Dockerfile
          failure-threshold: error

      - name: Determine image tags
        run: |
          if [ "${{ inputs.push_latest }}" = "true" ]; then
            echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
          else
            echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build and push PR image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.TAGS }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Lint Kubernetes Manifests
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: -summary -kubernetes-version 1.28.0 manifests/ manifests-preview/