name: Pull Request Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test-reusable.yml
    with:
      push_latest: false
    secrets: inherit
    permissions:
      contents: read
      packages: write

  deploy-preview:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: Inject PR Image Tags
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          sed -i "s|ghcr.io/$OWNER/\(.*\):latest|ghcr.io/$OWNER/\1:${{ github.sha }}|g" manifests-preview/*.yaml

      - name: Deploy Static Preview Environment
        run: kubectl --kubeconfig kubeconfig apply -f manifests-preview/

      - name: Test Availability
        run: |
          kubectl --kubeconfig kubeconfig rollout status deployment/backend-preview
          kubectl --kubeconfig kubeconfig rollout status deployment/frontend-preview
          kubectl --kubeconfig kubeconfig port-forward svc/frontend-preview 8080:8080 &
          sleep 5
          
          curl -X POST http://localhost:8080/api/add -d '{"message": "Pipeline automated test cookie"}' -H "Content-Type: application/json"
          curl -s http://localhost:8080/api/all | grep "Pipeline automated test cookie" || exit 1